### ISSUE TITLE
unavailable ressource

### ISSUE THREAD

**Issue by Luqswe** [aspnet/AspNetCore.Docs.de-de#40]
"Use the RegisterService.ps1 PowerShell script to register the service. From an administrative PowerShell 6 command shell, execute the script with the following command"

link to "RegisterService.ps1" is broken, file missing

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Hosten von ASP.NET Core in einem Windows-Dienst](https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@CeciAc We updated this topic and removed the script almost three weeks ago.

https://github.com/aspnet/AspNetCore.Docs/pull/12449

Do you know if it will take much longer for the localized versions to update?

**Comment by CeciAc** [comment]
@JasonCard can you please check this issue?

**Comment by JasonCard** [comment]
@guardrex @CeciAc I’ve confirmed source was fixed in [this commit](https://github.com/aspnet/AspNetCore.Docs/commit/3ffad41f661e8183c967e040a046b3918ea2642b#diff-b653a7d4cf7ece4356b11d10cd044cc5) on Mon 5/27 and handed off on Tue 5/28.
German is the only languages still not updated, so I'm following up on this and should be updated within a day or so.

**Comment by guardrex** [comment]
Sorry about the trouble there @Luqswe ... Engineering decided that they didn't want the PowerShell script in the topic any longer. They prefer that we show the individual commands in the topic. If the reader wants a script, they can put the individual commands into a script themselves. If you need to see the updated content immediately, you can translate the English version: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio

**Comment by JasonCard** [comment]
Hi @Luqswe 

Thank you for your feedback.
German article is also now updated, so resolving this issue.

Kind regards,
Microsoft DOCS International Team
