### ISSUE TITLE
Included "Add validation rules to the movie model" ...

### ISSUE THREAD

**Issue by Woife1978** [aspnet/AspNetCore.Docs.de-de#41]
is english in german view

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Hinzufügen der Validierung zu einer Razor-Seite in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hello, @Woife1978 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@CeciAc  here is the file
https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/RP-MVC/validation.md

I'm hoping https://github.com/aspnet/AspNetCore.Docs/pull/13125 fixes the problem.

**Comment by Rick-Anderson** [comment]
@CeciAc  I merged that change into live. How long until we know if that fixed it?

**Comment by Rick-Anderson** [comment]
@CeciAc  that didn't fix it. The entire include is not translated.

**Comment by CeciAc** [comment]
Thanks for checking @Rick-Anderson 
I assigned it to the engineer team in Brno, let wait for their reply next week.

**Comment by CeciAc** [comment]
Hello, @Woife1978 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
