### ISSUE TITLE
Abschnitt: Aktualisieren der Seite „Bearbeiten“ Tutorial für Razor Pages

### ISSUE THREAD

**Issue by HenriMuc** [aspnet/AspNetCore.Docs.de-de#43]
verwende VS019, was schon einige dinge (beim scaffolding) tut, die hier noch erwähnt werden (z.b. await)
folgendes funktioniert nicht im abschnit: Aktualisieren der Seite „Bearbeiten“: 
die table in Students.Details, welche die kurse zum student anzeigen soll :
@foreach (var item in Model.Student.Enrollments) - keine objektreferenz to an instance ... 
da ich noch lerne und keine experte bin, weiss ich nicht, wie man dies behebt

ANSONSTEN ist das tutorial für mich als anfänger, der von den webforms kommt, prima !
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor-Seiten mit EF Core in ASP.NET Core: CRUD (2 von 8)](https://docs.microsoft.com/de-de/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Ich bin nicht sicher, was Sie falsch machen, aber der Code funktioniert

Recommend you close this issue.

**Comment by CeciAc** [comment]
Hallo, @HenriMuc 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
