### ISSUE TITLE
Adding Field Database

### ISSUE THREAD

**Issue by HenriMuc** [aspnet/AspNetCore.Docs.de-de#46]
Filter (movie title) does not work : searchString not processed
I could not find out why

BUT Filter works only when "MovieGenre" is added in "Pages/Movies/Index.cshtml.cs  resp. OnGetAsync has the complete code 

IMPORTANT: note this is the first and only tutorial which works without any problems 
I have tried so far 5 tutorials on asp.net core with razor pages : all failed soon or later:
messages like missing reference, missing package, unnknown etc. showed up what I could not resolve. coming from webforms I was looking for a good tutorial to learn rarzor pages technique with EF

**this tutorial is perfect - many thanks**

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Hinzufügen der Suche zu Razor-Seiten in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Recommend closing this tutorial. We have many reports it works. 
@HenriMuc  if you can show where a bug is, open an issue from [this page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2#feedback)

**Comment by lichasu** [comment]
Hi @HenriMuc 

As this is not an issue with the localization, please follow Rick's instructions and create an issue in that repo.

Thanks @Rick-Anderson for the help!

I'll be closing this Issue now.
