### ISSUE TITLE
port configuration

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore.Docs.de-de#51]
In case someone hosts a windows application it would probably be best if this sample also contained the necessary snippets to configure that so the service which is running can be navigated to through a browser.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Hosten von ASP.NET Core in einem Windows-Dienst](https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by taori** [comment]
adding the following to appsettings.Production.json to this made it work:


	"Kestrel": {
		"EndPoints": {
			"Http": {
				"Url": "http://localhost:4300"
			}
		}
	},

**Comment by srvbpigh** [comment]
Hello, @taori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @taori 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/14193.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by taori** [comment]
@CeciAc Thank you. I appreciate the good docs :P
