### ISSUE TITLE
There should be a mention that implementations which use authentification won't work unless a https configuration is used

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore.Docs.de-de#52]
I ran into this issue when writing a service: https://github.com/aspnet/AspNetCore/issues/13804. Ideally if the docs mentioned this fact people who use this doc page won't spend time trying to figure this out. Perhaps at somepoint netcore might point out this requirement, but until then it's worth knowing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Hosten von ASP.NET Core in einem Windows-Dienst](https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @taori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
This can be closed ... we fixed it yesterday on https://github.com/aspnet/AspNetCore.Docs/pull/14208.

**Comment by taori** [comment]
@guardrex np. Just logged in to correct you but i see that you already noticed that this is a different issue :)
