### ISSUE TITLE
Whole migration guide is hidden

### ISSUE THREAD

**Issue by yutamago** [aspnet/AspNetCore.Docs.de-de#54]
"Click here to expand the list of packages no longer being produced" hides the whole following migration guide, not only the list of packages that are no longer being produced.

We just tripped over this, thinking it would be enough to just update the target framework.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrieren von ASP.NET Core 2.2 zu 3.0](https://docs.microsoft.com/de-de/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @yutamago
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yutamago** [comment]
Seems to be fixed now.
