### ISSUE TITLE
Übersetzungsfehler auf "Erzwingen von HTTPS is ASP.net Core"

### ISSUE THREAD

**Issue by Anamon** [aspnet/AspNetCore.Docs.de-de#55]
**URL:** https://docs.microsoft.com/de-de/aspnet/core/security/enforcing-ssl

Die deutsche Übersetzung des Artikels zeigt im Lead:

> Eine API kann verhindern, dass ein Client sensible Daten bei der ersten Anforderung sendet.

Das englische Original aber:

> No API can prevent a client from sending sensitive data on the first request.

Die Aussage des Satzes wird invertiert!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Erzwingen von HTTPS in ASP.net Core](https://docs.microsoft.com/de-de/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Anamon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @Anamon 

Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#feedback
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
