### ISSUE TITLE
wrong translation from en to de

### ISSUE THREAD

**Issue by VadzimN** [aspnet/AspNetCore.Docs.de-de#57]
Please, instead of 
"Zeigen Sie Beispielcode an, oder laden Sie diesen herunter"
write 
"Den Beispielcode anschauen oder herunterladen".

'Anzeigen' means 'show', not 'view'
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Gerüstbau mit Razor Pages in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @VadzimN
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @VadzimN 

 Thank you for your linguistic feedback. 
 
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because [as per closing period, this is not an option but actually an instruction. Therefore, the current translation is fine while the suggestion might be confusing to the reader.]

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@VadzimN  can you point out the English section so I can consider this?

Unfortunately, to a linguist, show and view are interchangeable, but in ASP.NET Core, they mean different things.

cc @scottaddie

**Comment by Rick-Anderson** [comment]
View or download example code

I thought it might be talking about a view, but that's not the case. I think the translation is OK here.

**Comment by VadzimN** [comment]
Hi Rick,

I have another opinion, but your are the decision-maker.

I would only like to know: do you have in your docs-team a translation-team? If yes, are there (native) german-speakers?

With kind regards,
Vadzim

**Comment by Rick-Anderson** [comment]
Wir haben deutschsprachige Muttersprachler, die Fragen wie diese prüfen können. Die Übersetzung erfolgt per Software.

Genau wie dieser

We have native german speaking linguists who can review questions like this. The translation is done by software.

Just like this
