### ISSUE TITLE
console statt PowerShell

### ISSUE THREAD

**Issue by ToninoFerrara** [aspnet/AspNetCore.Docs.de-de#59]
On page https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/adding-model instead of 'PowerShell' the title should be 'console' after 'Führen Sie den folgenden Befehl in der PMC aus:'

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Hinzufügen eines Modells zu einer ASP.NET Core MVC-App](https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @ToninoFerrara
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
No, powershell is correct. The PMC uses powershell. Recommend closing.

**Comment by ToninoFerrara** [comment]
On the same page, once PMC commands are shown in a box with label 'PowerShell' and one with label 'console'.

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/aspnet/AspNetCore.Docs/pull/15520
Please close
